name: Generate and Embed Mind Map PNG

permissions:
  contents: write

on:
  push:
    paths:
      - '02-data-analysis/mindmap.md'
      - 'scripts/export-markmap-image.js'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install markmap-lib markmap-render node-html-to-image

      - name: Generate mind map PNG from Markdown
        run: node scripts/export-markmap-image.js

      - name: Commit and push generated image
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add 02-data-analysis/img/mindmap.png
          git commit -m "Auto-generate mind map image from Markdown" || echo "No changes"
          git push
