name: Generate and Embed Mind Map PNG

permissions:
  contents: write

on:
  push:
    paths:
      - '02-data-analysis/mindmap.md'
      - 'scripts/export-markmap-image.js'

jobs:
  generate:
    runs-on: ubuntu-latest

    env:
      PUPPETEER_SKIP_DOWNLOAD: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install system dependencies for Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 \
            libatk1.0-0 libcups2 libdbus-1-3 libdrm2 libgbm1 libnspr4 libnss3 \
            libxcomposite1 libxdamage1 libxrandr2 xdg-utils wget ca-certificates \
            libu2f-udev libvulkan1

      - name: Install Node dependencies
        run: |
          npm install markmap-lib markmap-render node-html-to-image

      - name: Generate mind map PNG from Markdown
        run: node scripts/export-markmap-image.js

      - name: Commit and push generated image
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add 02-data-analysis/img/mindmap.png
          git commit -m "Auto-generate mind map image from Markdown" || echo "No changes"
          git push
