name: Update Mindmap PNG

on:
  push:
    branches:
      - main # Or master, or your default branch
    paths:
      - '02-data-analysis/mindmap.md'

jobs:
  build-mindmap:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Required to push the new PNG to the repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Cache npm packages for faster subsequent runs
          cache: 'npm'

      # 1. Install dependencies locally (no -g flag)
      - name: Install Dependencies
        run: npm install markmap-cli puppeteer

      # 2. Generate HTML using npx
      - name: Generate HTML from mindmap.md
        run: npx markmap-cli --no-open 02-data-analysis/mindmap.md -o 02-data-analysis/img/mindmap.html

      - name: Generate PNG from HTML
        run: node .github/scripts/export-markmap-image.js 02-data-analysis/img/mindmap.html 02-data-analysis/img/mindmap.png

      - name: Commit and push PNG
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add 02-data-analysis/img/mindmap.png 02-data-analysis/img/mindmap.html
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: Auto-generate mindmap assets"
            git push
          fi