name: Generate and Embed Mind Map PNG

permissions:
  contents: write

on:
  push:
    paths:
      - '02-data-analysis/mindmap.md'
      - 'scripts/export-markmap-image.js'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node dependencies
        run: |
          npm install markmap-lib markmap-render node-html-to-image puppeteer

      - name: Manually install Chromium
        run: |
          mkdir -p ~/.cache/puppeteer/chrome/linux-138.0.7204.92
          curl -Lo ~/.cache/puppeteer/chrome/linux-138.0.7204.92/chrome-linux64.zip https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/1211803/chrome-linux64.zip
          unzip ~/.cache/puppeteer/chrome/linux-138.0.7204.92/chrome-linux64.zip -d ~/.cache/puppeteer/chrome/linux-138.0.7204.92
          chmod +x ~/.cache/puppeteer/chrome/linux-138.0.7204.92/chrome-linux64/chrome

      - name: Set CHROME path
        run: |
          echo "PUPPETEER_EXECUTABLE_PATH=$HOME/.cache/puppeteer/chrome/linux-138.0.7204.92/chrome-linux64/chrome" >> $GITHUB_ENV

      - name: Render Markmap PNG
        run: node scripts/export-markmap-image.js

      - name: Commit and push image
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add 02-data-analysis/img/mindmap.png
          git commit -m "Auto-generated Markmap PNG" || echo "No changes"
          git push
